### ISSUE TITLE
Feature suggestion: Search seeds incrementally from seed 0

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#1]
This tool almost fits one of my seed finding goals, problem is it uses random seeds instead of searching from seed 0.

What I want to set is:
1. Minecraft 1.12.2
2. ALL major biomes within 2048 of 0,0 w/ ice spikes, flower forest, sunflower plains.
3. Seeds 0 through 4.3 billion

1 and 2 That was super easy to do with the tool, but not 3.

Searching seeds from seed 0 incrementally would be helpful as it means it would be possible to find similar seeds on bedrock edition, since bedrock only has the 32bit seedspace (seeds 0 - 4.3 billion). The option to search incrementally from seed 0, would be very helpful for me.  As they correlate pretty closely to the bedrock edition seedspace. Thanks.

I think the program searches in blocks of 65536 seeds, so searching in increments of those (seeds 0-65535, then scan seeds 65536-131071, seeds 131072-196608, etc, and so on)

![image](https://user-images.githubusercontent.com/23464599/103668647-5148df00-4f45-11eb-9f31-b81c1ec22ff1.png)

-----------------------------------------

Also, could we save the list of viable seeds to a text file?

-----------------------------------------

Also, side question

When I tick the "all major biomes" box, does it require the parent biome or is it the general biome type? What if I tick the regular "Birch Forest", but only "Birch Forest Hills M" is within the radius, would it throw out the seed or would it still pass?

**Comment by Cubitect** [comment]
Currently, the search is NOT random, but for significant performance reasons it is a little more complex than incrementing the seed by 1 in each pass.

In general, the lower 48-bits of the seed get incremented and then, as you have correctly noticed, the top 16 bit are segmented and distributed among several threads.

I did it this way because the majority of features have some component to them that allows me to rule out 48-bit seeds right away. On the flip side once I have found a suitable 48-bit seed, all upper 16-bit values become candidates and I can look for suitable biomes in any seed of this family of 65536.

If you only use the biome filter, there is indeed currently no benefit from searching this way, since the biomes require a full 64-bit seed. (However, this won't be the case in the future as there are some biomes can be judged by the lower 48-bits alone).

Regarding your request, I don't have bedrock edition and I know little about it and thus was not aware that they only have 32-bit seeds. I could add an option to limit the upper 16-bits to zero, effectively allowing only seeds between 0 and 2^48, but in the current design this will restrict the search to a single thread. I am also concerned how the negative seeds correspond to Java edition. Are they equivalent to the range 2147483649-4294967296?


Right now there is no file export option, but you can right-click on the matching seed list and select "Copy list to clipboard" and then paste the list into a text file.


I use the term major biome just to describe biomes that are generated at a certain point early in the generation process, other variants will be derived from those later on. However, currently if you select `birch_forest` the program will search for seeds that actually contain a `birch_forest` while `birch_forest_hills` will not suffice. I plan to add some option to restrict the biome filter to a certain generation layer, which means that you will be able to search for certain groups of biomes by aborting the generation process early. Such a filter would also be faster, but in some ways less accurate.

If you are looking for a diversity of biomes and are not concerned about a few false-negatives than I suggest that you also add the "All temperatures cluster" filter and put it before the biome filter in the conditions list. This should speed up the search a fair amount.

**Comment by Delvin4519** [comment]
Only positive Java seeds use the bedrock seedspace, so all Java seeds 0 through 4294967296 have a bedrock equivalent. The last bit becomes negative in bedrock, so that's why negative bedrock seeds are positive in Java edition. For the "starting 48 bit seed", this means the search ends at 2^32 instead of 2^48.

I think the "all temperature cluster" uses a layer higher up (Speciallayer 1:1024) for faster speed and diversity. However, all the other biomes use the bottom most layer I'd assume.

If we had access to the BaseBiomesLayer 1:256 we could search for specific biome types without worrying about the hill variants creating false negatives, although it loses a bit of precision (1:256 scale), it would increase search speed. It works for me to be honest.

I think the most relevant layers that users could use to search is the SpecialLayer 1:1024, BaseBiomesLayer 1:256, and the HillsLayer 1:64. Searching SpecialLayer 1:1024 can allow users to find large areas of hot or snowy biomes (i.e. a 5x5 hot biome area) or ocean and non ocean areas.

![image](https://user-images.githubusercontent.com/23464599/103697639-3343a480-4f6e-11eb-9d1d-d26e01dc0f9f.png)

**Comment by Delvin4519** [comment]
I have been tinkering around with the program for a bit, and I managed to find some interesting stats
![image](https://user-images.githubusercontent.com/23464599/103909731-0ad4bb00-50d2-11eb-97e6-bd7164a088be.png)

The existing release has the 3x3 All temperatures cluster option. This can speed up the search by filtering out 1 in every 93,956 seeds. However there plenty of use cases where a 5x5 All temperatures cluster can be useful, since it could still speed up the search by filtering out, I would guess like 1 in 1,000 seeds ish. I'd think it's just a slight modification to the 3x3 option by expanding the 3x3 to a 5x5 area and adding it as a separate option. Anyways, an option for users to filter out their own  SpecialLayer 1:1024 query, can speed up any seed finding by a whole lot, as it is a very critical and defining layer, defines sizes and positions of hot climate zones, snowy zones, 

---> 3x3 temperature cluster
---> 5x5 temperature cluster
---> SpecialLayer 1:1024

------------------------

I also know of a way to literally double the seed searching speed. It's the use of shadow seeds and exploiting this fact. Basically, the 64 bit seed space has only 2^63 unique land biome noise maps. 

So once a 48 bit structure seed is found, if any of the 65536 seeds has matching biomes, then a corresponding 48 bit structure seed will also have 65536 seeds with matching biomes which could also become candidates.
![image](https://user-images.githubusercontent.com/23464599/103912749-ae739a80-50d5-11eb-89e2-a8776101079b.png)

However there are some edge cases where shadow seeds are not desired, such as having duplicate seeds for each unique noise map if a user isn't searching for specific structures or ocean variants
![image](https://user-images.githubusercontent.com/23464599/103920034-ca2f6e80-50de-11eb-8d80-1884ed3d2014.png)

-------

The current released version searches via the first 48 bits, a.k.a the structure seed. I do like the current functionality where I can manually override the structure seed. I typed in the structure seed with the infinite mineshafts and I easily found 28 candidates with all biomes within 2048 with the infinite mineshafts in no time at all.

While we have the 48 bit incremental with the upper 16 bits limited to 0, I'm not sure if it's more useful than just swapping the 16bits around from the back to the front. It will still be incremental and searches through the bedrock seedspace at first, but there wouldn't be a need for a hard coded 2^48 limit I think. It'll still scan threads in blocks of 65536 seeds (Seeds 0-65535, 65536-131071, 13072-etc, etc). The upper bits are limited to incremental, instead of 0. Or a user could type in a random number and start searching from a random block of seeds. The bedrock 32 bit seed space would end after the 65536th incremental chunk of 65536 seeds (positive 4.3 billion, equal to 2^32, maximum bedrock seed, note the count starts from seed 0, not seed 1). 

Of course it's more complicated, and stuff has been updated and changed, so I could be all wrong, but just my thoughts.

**Comment by Cubitect** [comment]
Wow that is a lot to unpack.

#### Bedrock support

After a little research I don't see an easy way of supporting Bedrock. The biome generation does differ to a fair extent and the structure generation does not work at all. I'm still not entirely sure, but I think the reason is that the use of 32-integers in the world generation on Bedrock is much more extensive to the point that large sections of the code in cubiomes would need to be rewritten and a new version management introduced, and I don't have the references or motivation to do that. Regarding just the biome generation, Earthcomputer has at some point contributed a bedrock support version for layer BIOME 1:256 addressing [MCPE-69322](https://bugs.mojang.com/browse/MCPE-69322). However, it appears that this is not sufficient, ocean variants are determined differently in Bedrock and if chunkbase.com is to be believed, then I would guess that the Hills/Edge layers seem different as well.

#### Further filter options

You have mentioned expanding "All temperatures cluster" and asked for more customization at layer scale 1:1024. I will likely introduce something like that at some point, but understand that "All temperatures cluster" is not simply a test that generates Special 1:1024 and compares. Instead it exploits that you can check for special variations without generating anything. Specifically for getting all temperatures as close together as possible you require all 8 categories in a 3x3 grid. Testing for the required special variants allows the filter to be almost 40 times faster than it would be otherwise. However, this speed-up will will not scale to areas above 3x3, as they will lack the same diversity requirements.

Shadow seeds have, for the most part, the same biome generation, but they differ on the lower 48-bits and thus they DO have different ocean variants and different structure placements. Unfortunately, heavily structure restricted seeds (like quad-huts) are so rare that you will basically never hit another one if you change the lower bits like that. Options for shadow seeds may be useful to check in situations where the biomes are the main problem, with somewhat relaxed structure restrictions.

Regarding the search order, you cannot change it that easily because for quad-structures only a small subset of 48-bits get checked (merely counting to 2^48 would take many hours). A bunch of modular arithmetic, as well as some pre-computed lists are involved, in particular regarding the lowest 20-bits for quad-huts, such that only a handful of values have to be checked. Distributing the lower bits onto several threads in a sensible way is therefore more complicated than using the upper 16-bits. Otherwise a parallel incremental search might be limited to biomes-only.

**Comment by Delvin4519** [comment]
Yea, the kicker is the lack of 64 bit seeds on bedrock, as it means only 1 out of 4.3 billion seeds have a rough equivalent seed on bedrock. It appears though the maps are pretty much the same between java and bedrock up to BaseBiomesLayer 1:256, then it diverges after that. As such, that's the only reason bedrock maps have even vague similarities to their Java edition counterparts. Specific biome shapes and structures on bedrock edition have no documentation. To be honest, it's better than nothing, as there's no other way to find bedrock seeds other than chunkbase.com or to search seeds from seed 0. 

Even a basic search for bedrock seeds with "all biomes within 2000 blocks", which is a 1 in 2,014 seed, is simply not possible without a search from seed 0, and searching 2,000 seeds by hand is tedious.

I have overseen a program to find large mesa and megataiga biomes by using SpecialLayer 1:1024, and restricting that to the 32bit seed space, and sure enough, there were 8 bedrock edition seeds with a large mesa biome and megataiga, in the whole bedrock seed space.

I appreciate the explanation for search order and shadow seeds.

**Comment by Cubitect** [comment]
With v1.3 there is now support to search through all 64-bit seeds by grouping seeds on the least significant bits into work items, these are then distributed among the threads. This is pretty much as close as you can get to searching incrementally from 0 while utilizing multiple threads.
