### ISSUE TITLE
this is a suggestion

### ISSUE THREAD

**Issue by WindyCloudCute** [Cubitect/cubiomes-viewer#104]
It is recommended to add a block cache mechanism to avoid wasting CPU resources.

**Comment by WindyCloudCute** [comment]
This operation is mainly used to optimize the smoothness of viewing. When the program is zooming in and out of blocks, it often freezes, and the blocks that have been loaded before are repeatedly calculated, resulting in a decrease in smoothness.

**Comment by Cubitect** [comment]
The application already makes extensive use of some queued caching, but since the update for MC 1.18 I had not done a review of how suitable it fulfills its job. For the new pre-releases I was able to make some improvements to the cache utilization and added an option for the user to change the cache size of the map view.
