### ISSUE TITLE
Searching Seeds from a File. Getting Different Results Each Time

### ISSUE THREAD

**Issue by masterwyatt** [Cubitect/cubiomes-viewer#108]
When I'm searching a list of seeds for a certain condition each time I search it I get different results each time even though i made no change to the conditions or the seed file. Strange Issue
![image](https://user-images.githubusercontent.com/66440657/154719283-ffeb6d12-8fd9-4b2e-9713-302693bec3cb.png)
![image](https://user-images.githubusercontent.com/66440657/154719339-99833e96-eafc-472f-9c05-863f36f0d8f0.png)

**Comment by masterwyatt** [comment]
Ok I think I know the issue.. So if I click start search its not showing up any seeds for results and then when i click to pause the search. It shows me the seeds its found but for some reason thinks its done even though it hasn't finished searching it

**Comment by masterwyatt** [comment]
I also tried searching 3000 Seeds for a shipwreck within 5000 Blocks... Yep, 5000 and got only 5 seeds back..

**Comment by Cubitect** [comment]
I did find a persistence issue between successive searches, although I'm not sure that can explain the exact problem you're having.
Does this issue persist in the release of 2.0?

**Comment by Cubitect** [comment]
Actually I'm pretty sure I know what this was. When you stop a search the matching seeds that each thread has found, but has not yet submitted would be added to the results list. The extent to which this would occur depends on your search item size and number of threads.

This is no longer relevant for the newest versions, since the search management has been redesigned.
