### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by Nicktionary25** [Cubitect/cubiomes-viewer#111]
So when i try to disable the stop on results button it does not work i tried everything i can do

**Comment by Cubitect** [comment]
I works fine for me. It's a checkbox though, not a button. When checked, the search will try to gracefully terminate when a matching seed is found, otherwise the search continues until you either abort the search, a maximum number of seeds is exceeded, or the end of the search space is reached.

If you still have trouble with a specific search in the latest version then please provide a save file for the search you are trying to perform (File > Save session).

**Comment by Cubitect** [comment]
On further reflection this was most likely the issue described by #120 and should now be fixed.
