### ISSUE TITLE
Feature Request: Ability to label conditions

### ISSUE THREAD

**Issue by dragon3025** [Cubitect/cubiomes-viewer#113]
Once you have a few conditions, it becomes hard to remember what's what, so you have to click on them one by one to see what they're doing so you can find the one you want to edit.

If you could give a condition a optional label that would appear in the list, it would help a lot. If you could also give it a custom color that would be help even further.

**Comment by Cubitect** [comment]
Arbitrary descriptions for conditions would not be that easy to implement. By design, conditions are stored as small, raw data blocks of constant size. So a comment would probably be limited to a short maximum length of maybe around 16 characters. Custom colors would be possible, but I would like to reserve that for potential future use.

How many conditions are you using that this becomes a problem? I don't think I have ever needed more than 9, and so far I have generally found the summaries sufficiently descriptive. I would lean more towards adjusting the generated summary than adding custom texts.

But I would like to point out that you can now save a whole filter with a small
description in v2.1: File > Load filter preset...

**Comment by dragon3025** [comment]
That's about the same amount I was using. I had a lot of filters that said "biome filter", and it started becoming hard to tell what's doing what, but I overcame this by using a notepad to keep track. Made up examples:

1. No deserts <512
2. Forest Variant <32

I love the new filter saving feature.
