### ISSUE TITLE
Feature Request: Ability to disable conditions and/or a number in the condition list showing how many seeds passed it in the since the last search.

### ISSUE THREAD

**Issue by dragon3025** [Cubitect/cubiomes-viewer#114]
This would help to find conditions that might be too hard for seed searching.

**Comment by Cubitect** [comment]
It is now possible with v2.1.0 to disable conditions and I have added a search speed indicator which should make it significantly easier to gauge the performance.

However, I don't think counting the condition checks will be that meaningful, since the evaluation process can be quite complex.

The search is performed in several search passes (for example with and without biome checks) and determines continuously whether it is worth examining a seed further with more performance expensive checks. So conditions may effectively be checked multiple times or not at all for the same seed with wildly different time requirements, depending on the search type, the type of conditions and their relative dependencies.
