### ISSUE TITLE
Feature suggestion: add an analyzer tab to cubiomes viewer

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#13]
Something like this, 

![image](https://user-images.githubusercontent.com/23464599/106484700-df997d80-647d-11eb-9a6a-35f89ab01eb2.png)

**Comment by Cubitect** [comment]
I actually wanted to add an analyzer tab right from the start. It's the reason why "Search" is in a tab-widget to begin with. The problem was that I wanted to include information about quad-huts and the like. I found that it ended up with an awkward layout in the GUI and that feature ended up with it's own dialog. If I have a suitable list of interesting info to display I will probably add a tab(s). A simple list of the biomes/structures in a given area might be good start, so I might add this for v1.4.

**Comment by Cubitect** [comment]
Analysis tab has been added in 1.5, although I the functionality will likely change a little over the next releases.
