### ISSUE TITLE
Garbled code

### ISSUE THREAD

**Issue by BXY7429** [Cubitect/cubiomes-viewer#132]
issue: garbled code
system info: win11 pro

description:
seed + threads process + map cache + autosave show up a code like this "》〇【」" and "〈「"
i tried to re-install this program but i found out that this progam had configuration file didn't delet, and i can't find the path and delete it. i also tried to restart my pc but it doesn't work
i tried to download other versions of the exe file but still shows garbled code
files:
![image](https://user-images.githubusercontent.com/106784761/171762640-f6372084-e135-483c-831a-f3d41aaf239c.png)
![image](https://user-images.githubusercontent.com/106784761/171762141-d65faed5-4799-4c8b-8912-20db9d10bec2.png)

questions:
what is the configuration file path?
how should i solve it?

please pay attention to check thank you

**Comment by Cubitect** [comment]
The application uses the standard Qt path: [QStandardPaths::AppConfigLocation](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum) for its configurations.

However, I very much doubt that will fix your problem. From the screenshot, this appears to be a Font issue. The numbers are consistent with the Hexadecimal, but the digits are substituted for weird symbols. I don't know what could cause a problem like that. 

The precompiled binaries are built statically with a Windows 10 VM, and shouldn't really behave differently. I can only guess that Win 11 does something weird with the fonts, or that there is a bug in Qt. Do the digits 0-9 look okay when you open the  [DejaVuSans.ttf](https://github.com/Cubitect/cubiomes-viewer/blob/trunk/rc/fonts/DejaVuSans.ttf) font in this repository directly on your system somehow (not sure if Windows has a True Type Font previewer that you can use, otherwise you might need to install the font)?

**Comment by Cubitect** [comment]
I did some experimentation, and it seems Qt has some initialization issues on Windows when loading resources and is inconsistent how they are applied. Loading the fonts later during the startup process seemed to help for some reason, and I have included these changes with the latest v2.2.2 patch. Not sure if this fixes your weird broken texts, but let me know if it does.

**Comment by BXY7429** [comment]
two days ago, i tried run the program in my windows sandbox it works perfectly fine (no garbled code)
im not good at computer and porgaming, do u know how to solve it? i don't really understand =(

**Comment by Cubitect** [comment]
A quick search yielded a very similar problem described [here](https://answers.microsoft.com/en-us/windows/forum/all/corrupt-windows-font-numbers-in-weird-characters/fed6ed23-e28f-4a6c-9ce6-794085f96725) in the Microsoft forum. They seem to have had success fixing their problem by changing the system locale to something else and then back again.
