### ISSUE TITLE
End Bugs and features

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#134]
### Bugs:
all on seed -2756212613780611164 playing on 1.16.1

Wrong gateway locations (think they exist but don't)
/tp @p 370426 ~ -8024
/tp @p 369990 ~ -7840

Wrong End city Locations:
/tp @p 370304 ~ -7984 (think it exist but doesn't)

Wrong terrain generation:
Doesn't display the many rings of void and end terrain generation
versions there this type of generation occurs: https://bugs.mojang.com/browse/MC-159283

Summary Pic:
![image](https://user-images.githubusercontent.com/106852406/172019927-519c951e-c5cd-4beb-b372-0f5599bb376b.png)
Example pic of end rings (keep in mind not all mc versions have this)
![image](https://user-images.githubusercontent.com/106852406/172020272-e481ab15-d2ab-480f-9089-51c2e1ec3ca0.png)

### New Feature?
Could it be possible to add something like "Outer dragon gateway" structure to find. Especially what I'm talking about is where the game places a gateway portal when you go through one on the main island. Summary of gen it is draws a straight line from 0,0 through the fixed coord on main island til it hits the outer ring (there are more details but that is basically how it works)
![image](https://user-images.githubusercontent.com/106852406/172020563-f08331b0-2048-435a-991d-f17d07942ab1.png)

**Comment by Cubitect** [comment]
I knew about the outer end voids, but originally decided against supporting them because my implementation for the End biome generation is very different and simulating floating point overflows would be rather difficult. However it turns out these voids occur simply where the euclidean distance to (0,0) has an integer overflow and is negative. So it was actually rather simple to support now with v2.4.0. This also means it would be incredibly simple to fix on Mojangs side...
