### ISSUE TITLE
Feature request on structure seeds

### ISSUE THREAD

**Issue by 69b69t** [Cubitect/cubiomes-viewer#146]
Would it be possible to add a search type that only searches for a matching structure seed? (Like the 48-bit family blocks, but without the biome check)

**Comment by bogdan-barbu** [comment]
What would be useful for, out of curiosity? Because the only practical reason for having this in cubiomes-viewer, as far as I can see, is so that people can do a biome check later but... that kind of defeats the point of separating them in 99.99% of situations (who's going to generate a huge list of biome-based lists and then structure-based lists because they are individually useful and then cross-reference them?). All of this is already possible with cubiomes, though. It seems more reasonable that weird use cases should be implemented using the library than cramming every possible searching feature in one application. Would just mean more maintainability and more confusion for part of the user base.
