### ISSUE TITLE
Feature Request: Unlimited Scale

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#162]
Add a setting that allows you to zoom out far beyond the max 1024 scale. It would be a setting to push your pc to the max. (you can put a warning on it saying program will crash at some point).

Just a fun setting to mess around with. Not hugely needed/important

**Comment by Cubitect** [comment]
Originally there wasn't any limit to the scale, but people reported several issues, so I set the limit to 1:1024 since that's more or less the limit where you won't be able to discern any useful information anymore.
I'm guessing this request is a follow up from the addition of the outer end voids.

I made some optimizations and expanded the scale limit to 1:4096, so you'll now be able to see a fair portion of the entire world. I guess the tool will start using more memory at that point, but I think its fair to blame the user in that scenario.

If you still want to bypass the scale limits you can always set a value in the config file before starting the tool.
(Probably located in `~/.config/cubiomes-viewer` or `%AppData%/Local/cubiomes-viewer`.)

**Comment by mooing-cowmilk** [comment]
I might be blind but I don't see it in either location.
%AppData%/Local/cubiomes-viewer exists for me but only has 3 files (quad_barely, Quad_ideal, and session)

Assuming ~/.config/cubiomes-viewer means my home directory C:\Users\[my user] , I don't see a config file there

**Comment by Cubitect** [comment]
Apparently I was mistaken. The tool uses [QSettings](https://doc.qt.io/qt-5/qsettings.html#locations-where-application-settings-are-stored) for the UI settings, which on Linux is just a file in the same location as [QStandardPaths::AppConfigLocation](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum), so it's just another file or directory in `~/.config`, but on Windows it evidently resolves to an entry in the system registry. That's pretty inconvenient.

**Comment by Cubitect** [comment]
In 2.6.0 you can now manually specify a map scaling with the goto dialog within a much larger range than you can get by scrolling.
This way you can't accidentally get to a problematic scale, but the user can override the limit to a practical extent.
