### ISSUE TITLE
[Feature Request] Progress bar?

### ISSUE THREAD

**Issue by pastelneigh** [Cubitect/cubiomes-viewer#165]
Hey there! I'm loving using this program, and was wondering if something like a progress bar would be possible to implement?
When analysing large ranges, it'd be awesome to see how long it has left to go! 

Thanks for your hard work :) 

-Edit-
I'm referring to the analysis tab here, should have made that more clear!

**Comment by mooing-cowmilk** [comment]
![image](https://user-images.githubusercontent.com/106852406/189672356-3b362412-27eb-4bd3-a73c-d0c575947c17.png)
There is one for the search tab, unless your referring to the Analysis tab?

**Comment by pastelneigh** [comment]
Yes, sorry! I'm referring to the analysis tab! I should have made that more clear in my post! My apologies.

**Comment by Cubitect** [comment]
The analysis has a progress display that shows how many seeds have been checked from the seed list:
![analysis_progress](https://user-images.githubusercontent.com/15094581/201534442-aa1ed2c9-e9b1-416f-b2ab-94d944c4061a.png)

However, there is no progress indicator for individual seeds since the analysis, in general, does not follow a clear progressive algorithm, and how much time any of the requested checks take for a specific seed, is highly situational, so any progress report would be pretty much useless.
