### ISSUE TITLE
Feature request: Control over progress

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes-viewer#2]
It would be nice if there were a feature that would enable to pause/start the seed finding and also to save the current progress to a file and continue your search later. Some searches take a really long time to compute so it would be beneficial not to restart the search every time or to go through hoops to avoid it.

**Comment by Cubitect** [comment]
You can copy and paste seeds from the matching seeds list and then save them to a file, but I can add designated menu options for seed list export and import.

The search is sequential and occasionally the "Starting 48-bit seed" should update during the search (the interval in which this happens depends on your search criteria and hardware). This practically functions as a save point, since if you press the "Start search" button again (after clicking the stop on results button or aborting) the search will continue from that point on. If you abort the search you will loose the progress into the family of 65536 - top-16-bits seeds (only if you use multi-threaded ordering), but for long calculations that should not be too much of an issue.

**Comment by Cubitect** [comment]
I have added an option to save and load the progress including:
* the current 48-bit seed
* the result seed list
* the search settings

That should hopefully be more convenient to use.
