### ISSUE TITLE
Doesn't display all structures

### ISSUE THREAD

**Issue by tunaflsh** [Cubitect/cubiomes-viewer#263]
The world generation in 1.20 isn't the same for 1.20.1+. The viewer shows wrong world.

**Comment by Cubitect** [comment]
I'm not aware of any world generation changes between the 1.20 minor versions.
1.20.1 in particular was just a [minor hotfix update](https://minecraft.wiki/w/Java_Edition_1.20.1).

**Comment by tunaflsh** [comment]
Apologies. I just tested in 1.20 the seed `-4760463051109859295`.

Here is how the spawn looks like:
![image](https://github.com/Cubitect/cubiomes-viewer/assets/86954679/36da0ecf-f306-4b6f-9c23-11d36e9ecfaa)

And here is the seed viewer:
![image](https://github.com/Cubitect/cubiomes-viewer/assets/86954679/c9964da6-8a53-4d4f-be3e-edfdb2d4b8e3)

There are several factors that got me confused. There is a water part, that is considered desert biome, so the app didn't render water. That's on me, and I think it's not a bug. The other thing is a popular website [chunkbase](https://www.chunkbase.com/apps/seed-map#-4760463051109859295) shows only one desert temple at spawn.
![image](https://github.com/Cubitect/cubiomes-viewer/assets/86954679/7a7a7c91-7f60-4a5a-9f36-d0c17d8d8de6)

I assumed it was using the same app here, so I reported an issue.

**Comment by tunaflsh** [comment]
I just checked some pillager outposts. On the same seed, there is an outpost at `-2900 ~ -4400`.
![image](https://github.com/Cubitect/cubiomes-viewer/assets/86954679/835b8ea6-0cb7-4068-9095-46d9adddfe4b)

But the viewer doesn't find it.
![image](https://github.com/Cubitect/cubiomes-viewer/assets/86954679/4bd092ae-ae38-4eee-a861-0805e5e5f7ed)

I'll rename the issue, since it's not about support 1.20.1.

**Comment by Cubitect** [comment]
The missing pillager outpost in the cherry_grove was a bug that has been fixed in 3.4.1.

Incorrect positions for some desert temples is a known issue (see the readme). Desert temples check the actual block height before they generate, which cubiomes can't predict. Instead, it uses the climate depth as an approximation for the surface height, but there are some false positives and false negatives. I think chunkbase may also use the climate depth, but they may use a different cutoff value.

All the biomes are correct and don't necessarily reflect the in-game terrain.
