### ISSUE TITLE
Latest versions typo?

### ISSUE THREAD

**Issue by vico93** [Cubitect/cubiomes-viewer#330]
![image](https://github.com/user-attachments/assets/ce124095-870e-4f28-a118-aca26a1a7b39)

Basically seems like 1.21.1 got renamed to 1.21.2 and the future 1.21.2 was named 1.21.3 in the version list (and no 1.21).

I didnt saw any 1.21.3 version on official snapshot list, so i suspect it's a typo.

**Comment by Cubitect** [comment]
No that's correct. MC 1.21.2 is the current game version (which is feature complete, even if not fully released), while 1.21.3 is the future Winder Drop, which introduces the Pale Garden biome. Technically the designation of 1.21.3 is yet to be announced, but seems highly likely, opposed to 1.22 or similar.

The project only maintains the most current version of each main release, which worked fine so far. However, with the introduction of "Game-Drops", things become a bit more complicated. I have to specify 1.21.2, since it acts like a main release (representing 1.21.0 - 1.21.2), while the _most current_ version is 1.21.3, which is a significant feature change from a world generation view point.

**Comment by vico93** [comment]
Didnt knew about that, thanks for the information!
