### ISSUE TITLE
Bug: some biome searches are significantly quicker when a structure constraint is added

### ISSUE THREAD

**Issue by ellieeet123** [Cubitect/cubiomes-viewer#40]
It's kinda hard to explain this, so I'll give an example. I was running a 1:1 biome search to find a seed with every type of shore biome (beach, snow beach, stone beach, and mushroom shore) within a 25 block radius of 0, 0. With just that one filter, I got approximately 750K seeds per second (sps) scanned. If you want the search file for this, here it is:
#Version:  1.5.0
#Search:   0
#Progress: 11173888
#Cond: 07000000e7ffffffe7ffffff19000000190000000100000000000000000000001100000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080010600000000000000000000000000800106000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000

But then the bug appears when a ruined portal constraint is added. For some reason, with this extra constraint added and nothing else changed, the sps suddenly jumped up to approximately 66.3 Million. search file: 
#Version:  1.5.0
#Search:   0
#Progress: 1441759232
#Cond: 07000000e7ffffffe7ffffff19000000190000000100000000000000000000001100000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080010600000000000000000000000000800106000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000
#Cond: 1c000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000

**Comment by Cubitect** [comment]
The search is much faster because the seeds are checked in two passes (three if you count the seed generator for quad-structures). The first pass mainly checks if the requirements for structure positions are met. This is a lot faster and can potentially rule out many seeds at once (when using the "48-bit family blocks" search option). The second pass is more thorough and includes the biome checks.

In your case, the ruined portal has to sit exactly at the origin block and therefore the origin chunk. Given that the ruined portal could generate in any chunk of a 24*24 area inside the region, this means only 1 in 576 seeds goes on to the biome checks.

**Comment by ellieeet123** [comment]
Ooooh ok that makes a lot of sense. Thank you.
