### ISSUE TITLE
Feature request: Ammount of structures in a set distance

### ISSUE THREAD

**Issue by SissyFemBoi** [Cubitect/cubiomes-viewer#42]
- option where you just set the number of structures you want within a given distance

if you want more info just let me know.

**Comment by ellieeet123** [comment]
I'm pretty sure this already exists

**Comment by SissyFemBoi** [comment]
at least that I can see there is no option named structure which I can select and set the min amount of structure withing a set radius

**Comment by ellieeet123** [comment]
Whenever you make a structure constraint just set the area and then where it says "instances within area" just set that to whatever you want and then for example if you wanted four villages in 500 blocks then it will find that

**Comment by SissyFemBoi** [comment]
so can I use the Cubiomes to search for a seeds that have atleast 5 structure in total of any miss-mas of structure(E.G. 1 woodland mansion and 4 jungle temple or 4 Desert pyramid and 1 swamp hut, ETC..) in a set distance with just one option? I did not know that.

**Comment by ellieeet123** [comment]
Well you would have to make a new filter for each structure but yes it's possible

**Comment by SissyFemBoi** [comment]
Ok thanks for the input I am going to try to do only one Search and Search for Seeds that has total of 10 or more Stucture using only 1 search, so in that only 1 search I am going to find seeds that have 10 or more structures (E.G. 8 villages and 2 dessert pyramid or 4 jungle and 4 villages and 2swamp huts and 0 dessert pyramid) and the distance will be within 2048 radius from spawn.

just wondering can you tell me what you think I am saying in a short sentence? 

why is not my other feature request getting any atraction?

**Comment by ellieeet123** [comment]
What I think you're saying is that you add a bunch of filters so a search, one for each structure, and find a seed with lots of structures near spawn. And btw for the other one I would think it's because that would be very hard to implement into the code

**Comment by SissyFemBoi** [comment]
no I don't want to add bunch of filters for each structure, I want to add only one filter and that filter search for any structure.

**Comment by Cubitect** [comment]
As ellieeet123 already mentioned, you can specify a quantity for any of the supported structure filters, which should already cover most cases. However, each filter will be specific to a structure type since each structure type has to apply a different filtering algorithm.

Currently it is only possible to combine filters with an AND logic, i.e. all specified filters have to be met in order for a seed to pass. However, from what I gather you want to combine some filters via an OR logic, i.e. have 4 structures of A or B in an area.

Supporting filters with logical dependencies like that in a graphical interface seems like a nightmare to implement and use, so I have currently no intention to move into that direction. If you really need that much control over your search, you are better off coding a small search tool for your needs.
