### ISSUE TITLE
Biome Filter not working with 1.18

### ISSUE THREAD

**Issue by Cluedo97** [Cubitect/cubiomes-viewer#75]
using Biome filter and nothing is happening, tried with super simple filter with only forest and plains. Tried other filters like structure and it works I have also tried in 1.17 and it works.

I can also not abort searches as an instance is still running in the background which I can see in Task manager.

I am running in windows 11

**Comment by Mathbookair** [comment]
Are you using incremental or 48? 48 isn't working right now for me.

**Comment by Cubitect** [comment]
You are probably scanning too large an area. Biome generation for 1.18 is magnitudes slower than in previous version and right now the search doesn't deal too well with biome conditions that take too long for a single seed. You can try to use larger biome scales, but if you need to use slow conditions, you should also reduce the number of seeds per search items (under `Edit → Preferences`). If the problem persists, can you specify what you are searching for, or better yet, export your conditions (`File → Save progress`)?

**Comment by canyi2** [comment]
I also have same problem is not waking （or working slow）
![image](https://user-images.githubusercontent.com/95406510/144381943-52c2177a-3597-4877-9c38-2baff19144c2.png)
if I chose the stop button, but the system is still running ，unless the task manager kills the thread，我was running windows sever 2022

**Comment by Cluedo97** [comment]
I scanned a 4090 (2048x2048) area, is that too large because if it is then biome filter is completely useless right now. I would not call that working. and yes I used incremental

edit: My comment might have came out as a bit condescending, that's not my intent. You have made a very useful tool that I love to use. I just feel that it's a bit of false advertising saying that it works when it just doesn't. with 1.17 I get hundreds if not thousands of results in seconds but with 1.18 I get nothing.

**Comment by Cubitect** [comment]
I have tried to address the apparent issue at least somewhat in the latest update but I will provide a little context regarding the performance especially for searching and to manage expectations.

1) The new noise based biomes are something like a 100 times more computationally expensive to generate than the layered biome generation in earlier versions. I don't know why Mojang decided to switch to *these* algorithms, but that is what it is. My implementation is already quite well optimized and many times faster than Mojang's.

2) Furthermore, the Overworld biome filters up to 1.17 made use of some major optimizations that are simply no longer possible. I am not surprised if some biome checks take 100 000 times as long as they would have done before. (This is not an exaggeration.)

3) Despite this I am able to search for all kinds of biome conditions well enough, even in a 2048 block radius, although this is less useful than it used to be and it does require tweaking the conditions, adjusting the biome scale and reducing the search item size. I do agree that it is unfortunate that the default options that you may try first, resulted in a practical dead-lock. Admittedly there seem to be some major issues that I might have caught with more time, but I wanted to release with the 1.18 release. The newest update should be able to deal with this dead-lock and the "Abort" option should work again. However it simply is not possible to have anywhere near the same performance with 1.18 as it was for 1.17 and before. I am sorry if the capabilities for 1.17 have given you the wrong expectations.


On a side note, I notice that the fonts are terrible in that screenshot by canyi2 and the sizes are messed up. Is this a Windows 11 thing or otherwise a more common occurrence?

**Comment by Cluedo97** [comment]
Thank you for the info, real bummer it's so much slower now. But I tested the new version and it works much better now. 

Love the tool, will definitely keep using it :)

**Comment by canyi21** [comment]
I use an earlier version of Windows Server 2022. In fact, the kernel has not been upgraded to windows11 (the kernel version is 21h2). Thank you for your reply. I'll try again
