### ISSUE TITLE
Feature request: Ability to add end pillar heights and filter seeds using that

### ISSUE THREAD

**Issue by m-sarabi** [Cubitect/cubiomes-viewer#78]
Add the ability to add end pillar heights, it then calculates the pillar seed and only searches in seeds with that pillar seed.

**Comment by Cubitect** [comment]
At least for 1.9+ there are always the same 10 end pillars in each world.

**Comment by m-sarabi** [comment]
10 end pillars are at the same locations, but their height is different, that is I think about 3.5*10^6 different combinations, which with the right one finding a seed could be a lot faster if it only searches for those seeds

**Comment by Cubitect** [comment]
There are exactly 10 pillar designs which will all generate along a fixed ring. The only thing that changes is the order of those pillars, which depends on the lower 16 bit of the seed if I recall correct. In any case you can already search through a custom list of seeds and even a list of structure seeds. Admittedly this is not ideal if you want to look through all seeds with a particular pillar order, since this would be a list of about 4 billion structure seeds. I don't think this will help much in speedrunning, so I am curious, what would this be for?
