### ISSUE TITLE
Feature request: Search for any 'peaks' biome or other biome collections

### ISSUE THREAD

**Issue by luukio** [Cubitect/cubiomes-viewer#86]
Lovely work on the tool! 

Now with 1.18 out, one of the use cases I have with this tool is to find seeds that have either jagged_peaks, frozen_peaks or stony_peaks biomes next to spawn. It would be amazing if I can run one search where one of these biomes is there instead of all three needing to be. I am guessing its easy enough to make a biome category for that called Peaks?

**Comment by luukio** [comment]
Realising that the 'ocean' biome is not a category but indeed its own biome. 

Wondering if a biome collection is still possible to add. Like 'any_ocean' and 'any_peaks'. It will save a lot of repetition in terms of searches.

**Comment by Cubitect** [comment]
There are now several ways to achieve this in the new release 2.0:

The most straightforwards would be to use the "Match Any" flag in the 1.18 biome filter, which will trigger if *any* rather than all of the "required" biomes are present.

Another approach would be to use the climate noise filter and pose restrictions on the climate parameters. This is more efficient, but also more involved and will not work well for all biomes combinations.

The third method would be use the OR logic helper condition and attach different biome filters to it. This is not the best method for this use case and not very efficient, but it is very general.
