### ISSUE TITLE
Using Help: Quad Hut and Quad Ocean Monument

### ISSUE THREAD

**Issue by tsx8** [Cubitect/cubiomes-viewer#9]
Is it possible to find a seed that includes a quad hut and a quad ocean monument? If it's ok, how can I use this tool to find it?
![image](https://user-images.githubusercontent.com/42398191/104828969-d15a3780-58a9-11eb-9f01-7b07e005b55a.png)

**Comment by Cubitect** [comment]
In principle you can, and you already did it correctly. However, quad-monuments are several orders of magnitude rarer than quad-huts and you have found that there are no seeds at all which have both that close to spawn. You can make the search area much larger, but currently the tool has no ideal optimizations for this and the progress reports don't work too well in this scenario.

If you choose a small search area for the quad monument (say a square of 3 = radius of 1024 blocks) and a very large area (say 2000 = radius 512000 blocks) you should get some results. For a given seed you can also locate quad-huts in a world using the menu option 'Map' -> 'Scan seed for Quad-Huts...' and if there are any, you can view them with [right click] -> 'Show in map viewer'. Unfortunately this option does not exist for quad-monuments yet.

**Comment by Boobies** [comment]
I know we are kind of abusing this bug tracker but you haven't been on Discord for a very long time, as far as I could tell. :)

Could you explain how these squares relate to the number of blocks? What is the relationship between 3 and 1024 on the one hand and 2000 and 512000 on the other?

**Comment by Cubitect** [comment]
Structure generation occurs in the cells of a grid (of 512 blocks for swamp huts and ocean monuments). After some back and forth I decided to have the user input for the area of quad-structures in terms of this region size, because direct block coordinates would have an ambiguous meaning and turned out even more confusing.

This means for the input option of a square area for a quad-structure, you specify the side length of that square in terms of 512 blocks. Since the bounds of that range are included, if you enter "3" here, you actually have a ((3+1)*512-1) x ((3+1)*512-1) = 2047x2047 block area, centered on the origin (by default). The actual area is thus from (-1024, -1024) to (1023, 1023). Hence my statement of "radius of 1024 blocks". Likewise for "2000" the area will go from -512000 to +512511 on both axes.
